AdamGuidarini/MediTrak

app/src/main/java/projects/medicationtracker/Dialogs/PauseResumeDialog.java, app/src/main/java/projects/medicationtracker/Helpers/DBHelper.java, app/src/main/java/projects/medicationtracker/MainActivity.java
Medication schedule shows paused periods
=> Paused medications in schedule

app/build.gradle, app/src/main/java/projects/medicationtracker/Helpers/NotificationHelper.java, app/src/main/java/projects/medicationtracker/Receivers/EventReceiver.java, app/src/main/java/projects/medicationtracker/Services/NotificationService.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
Fixed bug preventing "Taken" button in notification from marking an edited notification as taken on Android 12+
=> Gradle update & notification bug fix

app/src/main/java/projects/medicationtracker/Dialogs/AddAsNeededDoseDialog.java, app/src/main/java/projects/medicationtracker/Dialogs/DoseInfoDialog.java, app/src/main/java/projects/medicationtracker/Fragments/MedicationScheduleFragment.java, app/src/main/java/projects/medicationtracker/Helpers/DBHelper.java, app/src/main/java/projects/medicationtracker/Interfaces/IDialogCloseListener.java, app/src/main/java/projects/medicationtracker/Interfaces/IScheduleItemTag.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_medication_schedule.xml
As needed meds are now distinct from scheduled meds
=> Distinct as needed doses in sched

app/src/main/java/projects/medicationtracker/AddMedication.java, app/src/main/java/projects/medicationtracker/Fragments/MyMedicationsFragment.java, app/src/main/java/projects/medicationtracker/MedicationNotes.java, app/src/main/java/projects/medicationtracker/SimpleClasses/Medication.java, app/src/main/res/values/strings.xml
Notes on changes to medications now auto-generate
=> Create note on med update

app/build.gradle, app/src/main/cpp/medicationtracker.cpp, app/src/main/java/projects/medicationtracker/Fragments/MyMedicationsFragment.java, app/src/main/java/projects/medicationtracker/Models/Dose.java, app/src/main/java/projects/medicationtracker/Models/Medication.java, app/src/main/res/layout/dialog_filter.xml
Fixing crashes when loading medication history
=> Fix loading history

app/src/main/java/projects/medicationtracker/Dialogs/AddAsNeededDoseDialog.java, app/src/main/java/projects/medicationtracker/Dialogs/DoseInfoDialog.java, app/src/main/java/projects/medicationtracker/Fragments/MedicationScheduleFragment.java, app/src/main/java/projects/medicationtracker/Helpers/TimeFormatting.java, app/src/main/java/projects/medicationtracker/Receivers/EventReceiver.java, app/src/main/java/projects/medicationtracker/Services/NotificationService.java, app/src/main/res/menu/main_menu.xml
- Crash fixes
- Changed Add Medication to + icon in Schedule
- Grouping notification fixes
=> Crashes from seconds having 1 digit

app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.cpp, app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.h, app/src/main/cpp/Sqlite3Database/Table/Table.cpp, app/src/main/cpp/medicationtracker.cpp, app/src/main/java/projects/medicationtracker/AddMedication.java, app/src/main/java/projects/medicationtracker/Dialogs/AddAsNeededDoseDialog.java, app/src/main/java/projects/medicationtracker/Dialogs/DoseInfoDialog.java, app/src/main/java/projects/medicationtracker/Fragments/MedicationScheduleFragment.java, app/src/main/java/projects/medicationtracker/Helpers/DBHelper.java, app/src/main/java/projects/medicationtracker/Helpers/NativeDbHelper.java, app/src/main/java/projects/medicationtracker/Helpers/TimeFormatting.java, app/src/main/java/projects/medicationtracker/MainActivity.java, app/src/main/java/projects/medicationtracker/MediTrak.java, app/src/main/java/projects/medicationtracker/MedicationHistory.java, app/src/main/java/projects/medicationtracker/Models/Dose.java, app/src/main/java/projects/medicationtracker/MyMedications.java, app/src/main/java/projects/medicationtracker/Receivers/EventReceiver.java, app/src/main/java/projects/medicationtracker/Receivers/NotificationReceiver.java
- Stopped notifications from firing if already taken
- Database will automatically update if when a the app updates
=> Do not send notification if taken

app/src/main/java/projects/medicationtracker/AddMedication.java, app/src/main/java/projects/medicationtracker/Helpers/DBHelper.java, app/src/main/java/projects/medicationtracker/Helpers/NotificationHelper.java, app/src/main/java/projects/medicationtracker/Workers/NotificationWorker.java, app/src/main/res/layout/activity_add_medication.xml, app/src/main/res/layout/dialog_add_note.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml
- Can add instructions to medication
- Instructions display in notifications
- Guards against duplicate notifications
- Additional null safety checks to prevent crashes on data import
- Preventing alerts for notification summary
=> Optional instructions in notifications

app/src/main/java/projects/medicationtracker/AddMedication.java
=> removed comment

app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.cpp, app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.h, app/src/main/java/projects/medicationtracker/Helpers/DBHelper.java, app/src/main/java/projects/medicationtracker/MainActivity.java, app/src/main/java/projects/medicationtracker/MediTrak.java, app/src/main/java/projects/medicationtracker/Receivers/EventReceiver.java
- Fixes for DB updates causing crashes
=> Crash on launch fixes

README.md, app/src/main/java/projects/medicationtracker/Fragments/MyMedicationsFragment.java, app/src/main/java/projects/medicationtracker/Helpers/DBHelper.java, app/src/main/java/projects/medicationtracker/Models/Medication.java, app/src/main/res/layout/fragment_my_medications.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml
- Updated styling for My Medications
- Updated README
=> Redsign my medication cards

app/src/main/java/projects/medicationtracker/Receivers/EventReceiver.java, app/src/main/java/projects/medicationtracker/Receivers/NotificationReceiver.java, app/src/main/java/projects/medicationtracker/Workers/NotificationWorker.java
- Fixed notifications not firing
=> More safety checks, notifications not firing fix

app/build.gradle, app/src/main/cpp/Sqlite3Database/Table/Table.cpp, app/src/main/cpp/Sqlite3Database/Table/Table.h, app/src/main/java/projects/medicationtracker/Settings.java, build.gradle
- Fixed errors setting date and time formats at the same time
- Guard for fixing notifications
=> Bug notifications don't work

app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.cpp, app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.h, app/src/main/cpp/medicationtracker.cpp, app/src/main/java/projects/medicationtracker/Adapters/HistoryAdapter.java, app/src/main/java/projects/medicationtracker/Dialogs/DoseInfoDialog.java, app/src/main/java/projects/medicationtracker/Fragments/MedicationScheduleFragment.java, app/src/main/java/projects/medicationtracker/Fragments/MyMedicationsFragment.java, app/src/main/java/projects/medicationtracker/Helpers/NativeDbHelper.java, app/src/main/java/projects/medicationtracker/Models/Dose.java, app/src/main/res/layout/dialog_dose_info.xml, app/src/main/res/values/strings.xml
=> Override dosages

app/src/main/res/values-es/strings.xml
As I can't find the vc25 branch, I pull it here.
I didn't translate it at first, because the string was empty. It's still empty in the english and the german versions.
=> Add missing translation

README.md, app/build.gradle, app/src/main/java/projects/medicationtracker/AddMedication.java, app/src/main/java/projects/medicationtracker/Helpers/DBHelper.java, app/src/main/java/projects/medicationtracker/Settings.java, app/src/main/res/layout/activity_settings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/locales_config.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
- Added Italian translation
- Added ability to change languages
=> Change language in settings

app/src/main/java/projects/medicationtracker/Fragments/MedicationScheduleFragment.java, app/src/main/java/projects/medicationtracker/MainActivity.java, app/src/main/java/projects/medicationtracker/Receivers/EventReceiver.java
- Notifications are not automatically dismissed when opening the app
- Marking a notification as taken removes that notification if open
=> Do not dismiss notifications in sched

README.md, app/build.gradle, app/src/main/java/projects/medicationtracker/Dialogs/OpenNotificationsDialog.java, app/src/main/java/projects/medicationtracker/MainActivity.java, app/src/main/java/projects/medicationtracker/Receivers/EventReceiver.java, app/src/main/java/projects/medicationtracker/Workers/NotificationWorker.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml
- Added "Take all" button to notifications
=> Update notifications with take all button

app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.cpp, app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.h, app/src/main/cpp/Sqlite3Database/DbManager/DbManager.cpp, app/src/main/java/projects/medicationtracker/Helpers/DBHelper.java, app/src/main/java/projects/medicationtracker/Models/Dose.java, app/src/main/java/projects/medicationtracker/Models/Medication.java, app/src/main/java/projects/medicationtracker/Models/Notification.java
- Fixed issue causing the app to crash when opening the schedule after importing data
- Fixes data imports where the last character was removed
=> Bug crash on launch

app/build.gradle, app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.cpp, app/src/main/java/projects/medicationtracker/Adapters/HistoryAdapter.java, build.gradle
- Fixed crashes when viewing history for as needed medications
- Displaying "N/A" for scheduled time in Medication History for as needed medications
=> History crash as needed

app/src/main/res/values-nl/strings.xml
I have add the Dutch translation.
Thanks!
=> Adding Dutch Translation

app/src/main/res/values-nl/strings.xml
Will see it into the next update ;) Thanks!
=> A fix for 2 strings not corrected translated. 

app/src/main/res/values-nl/strings.xml
Not urgent to make a new version for it as it's only one word, the rest of the Dutch translation would be fine now! Thanks!
=> It seems i frogot one string to make the correct translation

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.cpp, app/src/main/cpp/MediTrakCore/DatabaseController/DatabaseController.h, app/src/main/java/projects/medicationtracker/AddMedication.java, app/src/main/java/projects/medicationtracker/Fragments/ConfirmDeleteAllFragment.java, app/src/main/java/projects/medicationtracker/Fragments/MedicationScheduleFragment.java, app/src/main/java/projects/medicationtracker/Receivers/EventReceiver.java, app/src/main/java/projects/medicationtracker/Utils/NotificationUtils.java, app/src/main/java/projects/medicationtracker/Workers/NotificationWorker.java, build.gradle
=> Bug   mark taken not working

.gitignore, README.md, app/build.gradle, app/src/main/cpp/CMakeLists.txt, build.gradle, sqliteconfig.json
=> Fetch sqlite3 lib in cmake

app/src/main/AndroidManifest.xml, app/src/main/java/projects/medicationtracker/Receivers/EventReceiver.java, app/src/main/java/projects/medicationtracker/Utils/NotificationUtils.java, build.gradle
- Fixed notification summary persisting after all notifications were dismissed
- Restored exact timers for notifications (Android 12+ affected)
=> Ghost notifications
